### PR TITLE
Freemius Insights integration.

### PR DESCRIPTION
**Pull request by fs-contributor**

### CODE REVIEW

**Comment by ahmadawais** [comment]
@fs-contributor I have added freemius in there https://github.com/WPTie/CF7Customizer/releases/tag/1.0.1-beta

**Comment by fs-contributor** [comment]
We have briefly reviewed your code, and if we understand it correctly, you should comment the following logic that is responsible for forwarding the user to the "Welcome" page after activation:
1. `register_activation_hook( __FILE__, 'cfc_welcome_screen_activate' );`
2. `register_deactivation_hook( __FILE__, 'cfc_welcome_screen_deactivate' );`

You should remove it is since FS already takes care of the auto-forward for you. With your code, it makes a duplicate redirect, which is redundant.

**Comment by ahmadawais** [comment]
@fs-contributor Thanks! I just pushed an update to the master branch.

**Comment by ahmadawais** [comment]
@fs-contributor 
I have updated on the master branch of https://github.com/WPTie/CF7Customizer/
I am having issues. It keeps asking me to activate even after activating and there multiple same sites in the dashboard
http://jmp.sh/lcfDyYN
Kindly download the master and try it.

**Pull request closed without merging**
